#!/usr/bin/env python3

from pathlib import Path
import os
import yaml

project_root = Path(__file__).parent.parent
in_path = os.getenv("BASE_DEFININITION_PATH")
out_path = os.getenv("COMPONENT_DESCRIPTOR_PATH")

def read_data(path: str) -> str:
    with open(path, "r") as file:
        return file.read()

cd = yaml.safe_load(read_data(in_path))
cd["component"]["resources"].append({
    "name": "chart",
    "type": "helmChart",
    "input": {
        "type": "helm",
        "path": project_root.joinpath("charts", "k8syncer"),
        "repository": "/charts"
    }
})

with open(out_path, "w") as file:
    yaml.safe_dump(cd, stream=file, default_flow_style=False)
