#!/bin/bash -eu

# creates a dummy component descriptor

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
HACK_DIR="$PROJECT_ROOT/hack"

VERSION="$($HACK_DIR/get-version.sh)"
COMPONENT_REGISTRY="$($HACK_DIR/get-registry.sh --component)"

cat << EOF > "$COMPONENT_DESCRIPTOR_PATH"
component:
  componentReferences: []
  name: github.com/gardener/dummy
  provider: sap.com
  repositoryContexts:
  - baseUrl: ${COMPONENT_REGISTRY%%/*}
    componentNameMapping: urlPath
    subPath: ${COMPONENT_REGISTRY#*/}
    type: OCIRegistry
  resources: []
  sources: []
  version: v0.0.0-dummy
meta:
  schemaVersion: v2
EOF
