#!/bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
COMPONENT_NAME="k8syncer"
IMAGE_REPO="$($PROJECT_ROOT/hack/get-registry.sh --image)/${COMPONENT_NAME}"

source "$PROJECT_ROOT/.ci/ensure-go"
"${PROJECT_ROOT}/.ci/prepare-docker"
"${PROJECT_ROOT}/.ci/ensure-make"

(
  cd "${PROJECT_ROOT}"
  if [[ "$EFFECTIVE_VERSION" == *dev* ]]; then
    export ADDITIONAL_TAG="dev-$EFFECTIVE_VERSION"
  else
    export ADDITIONAL_TAG="latest"
  fi
  make docker-multi
)
