#!/bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
COMPONENT_NAME="k8syncer"
IMAGE_PREFIX="$($PROJECT_ROOT/hack/get-registry.sh)/${COMPONENT_NAME}"

# start docker daemon
launch-dockerd.sh

# configure credentials
mkdir -p "$HOME/.docker"
gardener-ci docker cfg --image "$IMAGE_PREFIX" > $HOME/.docker/config.json
