#!/bin/bash -eu

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
COMPONENT_NAME="k8syncer"
IMAGE_REPO="$($PROJECT_ROOT/hack/get-registry.sh --image)/${COMPONENT_NAME}"

CHART_FILE="${PROJECT_ROOT}/charts/${COMPONENT_NAME}/Chart.yaml"
CHART_VALUES_FILE="${PROJECT_ROOT}/charts/${COMPONENT_NAME}/values.yaml"

# update VERSION file
echo -n "$EFFECTIVE_VERSION" > "$PROJECT_ROOT/VERSION"

# update version and image tag in helm chart
sed -E -i -e "s@version: [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*@version: $EFFECTIVE_VERSION@1" "${CHART_FILE}"
sed -i -e "s@  tag: .*@  tag: ${EFFECTIVE_VERSION}@" "${CHART_VALUES_FILE}"

# update image registry in helm chart (usually doesn't change, but is easily forgotten if it does)
sed -i -e "s@  repository: .*@  repository: ${IMAGE_REPO}@" "${CHART_VALUES_FILE}"

# remove backup files (created by sed on MacOS)
for file in "${CHART_FILE}" "${CHART_VALUES_FILE}"; do
  rm -f "${file}-e"
done

echo "Version set to $EFFECTIVE_VERSION"
