apiVersion: v1
kind: ConfigMap
metadata:
  name: k8syncer-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |
    syncConfigs:
{{ .Values.config.syncConfigs | toYaml | indent 4 }}
    storageDefinitions:
{{ .Values.config.storageDefinitions | toYaml | indent 4 }}
