{{- if .Values.config.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: k8syncer-target
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  kubeconfig: {{ .Values.config.kubeconfig | b64enc }}
{{- end }}