{{- if or .Values.config.kubeconfig .Values.config.cluster }}
apiVersion: v1
kind: Secret
metadata:
  name: k8syncer-target
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- if .Values.config.kubeconfig }}
  kubeconfig: {{ .Values.config.kubeconfig | b64enc }}
  {{- else }}
  {{- range $k, $v := .Values.config.cluster }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
  {{- end }}

{{- end }}