{{- if .Values.image.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: k8syncer-image-pull
data:
  .dockerconfigjson: {{ .Values.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
{{- end }}
