{{- if not .Values.config.kubeconfig }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8syncer
  namespace: {{ .Release.Namespace }}
  labels:
    app: k8syncer
    role: k8syncer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}