{{- if not (or .Values.config.kubeconfig .Values.config.cluster) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8syncer
  namespace: {{ .Release.Namespace }}
  labels:
    app: k8syncer
    role: k8syncer
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}